In [0]:
import numpy as np
import time 
import sys


In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
l = range(5)
l

range(0, 5)

In [29]:
l[0]

0

In [30]:
l[1]

1

In [31]:
np.arange(1,5)

array([1, 2, 3, 4])

In [32]:
np.arange(1,5,2)

array([1, 3])

In [33]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [34]:
a=np.array([[1,2],[3,4],[7,2]])
a

array([[1, 2],
       [3, 4],
       [7, 2]])

In [35]:
a.shape

(3, 2)

In [37]:
a.reshape(2,3)


array([[1, 2, 3],
       [4, 7, 2]])

In [38]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [7],
       [2]])

In [40]:
a.ravel()

array([1, 2, 3, 4, 7, 2])

In [41]:
a.min()

1

In [42]:
a.max()

7

In [43]:
a.sum()

19

In [44]:
a.sum(axis = 0)

array([11,  8])

In [46]:
a.sum(axis = 1)

array([3, 7, 9])