###**Iteration in numpy**

In [0]:
import numpy as np


In [7]:
a = np.arange(12).reshape(3,4)
print(a)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
#Using normal for loop iteration
for row in a:
    for cell in row:
        print(cell)



0
1
2
3
4
5
6
7
8
9
10
11


###**nditer**

In [9]:
#For loop with flatten
for cell in a.flatten():
    print(cell)



0
1
2
3
4
5
6
7
8
9
10
11


In [10]:
for x in np.nditer(a, order='C'):
    print(x)

#C style ordering


0
1
2
3
4
5
6
7
8
9
10
11


In [11]:
#Fortan style ordering

for x in np.nditer(a, order='F'):
    print(x)







0
4
8
1
5
9
2
6
10
3
7
11


In [12]:
#external_loop

for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [13]:
#Modify array values while iterating

for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x
print(a)


[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [14]:
#Iterate two broadcastable arrays concurrently

b = np.arange(3, 15, 4).reshape(3,1)
print(b)


[[ 3]
 [ 7]
 [11]]


In [15]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
