### **Indexing and Slicing**

In [0]:
import numpy as np 
import sys 

In [20]:
n =[6,7,8]
print(n[0:2])
print(n[-1]) 

[6, 7]
8


In [21]:
a = np.array([6,7,8])
print(a[0:2])
print(a[-1]) 

[6 7]
8


In [43]:
a = np.array([[6,7,8],[5,6,7],[2,3,3]])
print(a)

[[6 7 8]
 [5 6 7]
 [2 3 3]]


In [26]:
#a[row,column]
a[1,2]

7

In [27]:
a[0:2,2]

array([8, 7])

In [28]:
a[-1]

array([2, 3, 3])

In [29]:
a[-1,0:2]                   

array([2, 3])

In [30]:
for row in a : 
  print(row)

  #prints the elements row-wise 

[6 7 8]
[5 6 7]
[2 3 3]


In [31]:
for cell in a.flat :
  print(cell)

#prints out all the element/flattens the array

6
7
8
5
6
7
2
3
3


### **Stacking and Splitting**

In [41]:
c = np.arange(6).reshape(3,2)
d = np.arange(6,12).reshape(3,2)
print(c)


[[0 1]
 [2 3]
 [4 5]]


In [42]:
print(d)


[[ 6  7]
 [ 8  9]
 [10 11]]


In [39]:
np.vstack((c,d))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [40]:
np.hstack((c,d))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [45]:
q = np.arange(30).reshape(2,15)
print(q)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [0]:
r = np.hsplit(q,3)

In [52]:
print("The first part is " ,r[0],"\n\n" "The second part is ",r[1],"\n\n" "The third part is ",r[2])

The first part is  [[ 0  1  2  3  4]
 [15 16 17 18 19]] 

The second part is  [[ 5  6  7  8  9]
 [20 21 22 23 24]] 

The third part is  [[10 11 12 13 14]
 [25 26 27 28 29]]


In [59]:
r = np.arange(12).reshape(3,4)
w = r > 4 ## Each element of r is compared with 4

print ("Elements of r :  ",r,"\n\n" "The result for comparing each element with 4 is : ",w)

Elements of r :   [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

The result for comparing each element with 4 is :  [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
